name: Collect Data

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # This workflow is triggered manually or on Wednesdays at 2320 UTC
  # This should be after Jagex updates the cache
  schedule:
    - cron: "20 23 * * 3" # Every Wednesday at 23:20 UTC

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: ğŸŸ¢ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: â˜• Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"
      - name: ğŸ“¦ Install dependencies
        run: npm install
      - name: ğŸ”§ Make all scripts executable
        run: chmod -R +x common tools/**/*.sh
      - name: â–¶ï¸ Run all tools
        run: npm run collect
      - name: ğŸš€âœ¨ Commit & Push Data Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github_actions
          message: "ğŸ”„ Auto-update: add new data ğŸ“¦"
